# https://github.com/probot/settings
_extends: .github
repository:
  name: sanity-typed-schema-builder
  description: Build Sanity schemas declaratively and get typescript types of schema values for free!
  homepage: https://saiichihashimoto.github.io/sanity-typed-schema-builder
  topics: sanity, schema, typescript, builder, zod
  private: false
branches:
  - name: main
    protection:
      required_status_checks:
        contexts:
          - Build
          - Lint
          - Test
